package postgres.dao;

import postgres.entity.State;

import java.util.List;

public interface StateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int insert(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int insertSelective(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    List<State> selectByPrimaryKey(Integer stateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(State record);

    List<State> selectByCountryByID(Integer countryid);
}