package postgres.dao;

import org.apache.ibatis.annotations.Param;
import postgres.entity.Student;
import postgres.entity.custom.CustomStudent;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Student record);

    /**
     * This method was generated by Xin An.
     * This method corresponds to the database table student
     *
     * @anxin
     */
    List<CustomStudent> selectAll();

    /**
     * This method was generated by Xin An.
     * This method corresponds to the database table student
     *
     * @anxin
     */
    int addStudent(Student student);

    /**
     * This method was generated by Xin An.
     * This method corresponds to the database table student
     *
     * @anxin
     */
    Student selectByStudentID(String studentid);

    /**
     * This method was generated by Xin An.
     * This method corresponds to the database table student
     *
     * @anxin
     */
    CustomStudent getStudentByID(String studentid);

    /**
     * This method was generated by Xin An.
     * This method corresponds to the database table student
     *
     * @anxin
     */
    List<CustomStudent> orderStudent(@Param("order") String order);
}