package postgres.entity;

public class CityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityid
     *
     * @mbggenerated
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.stateid
     *
     * @mbggenerated
     */
    private Integer stateid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityid
     *
     * @return the value of city.cityid
     *
     * @mbggenerated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityid
     *
     * @param cityid the value for city.cityid
     *
     * @mbggenerated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.stateid
     *
     * @return the value of city.stateid
     *
     * @mbggenerated
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.stateid
     *
     * @param stateid the value for city.stateid
     *
     * @mbggenerated
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }
}