package postgres.entity;

public class City extends CityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityname
     *
     * @mbggenerated
     */
    private String cityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityname
     *
     * @return the value of city.cityname
     *
     * @mbggenerated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityname
     *
     * @param cityname the value for city.cityname
     *
     * @mbggenerated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }
}