package postgres.entity;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countryid
     *
     * @mbggenerated
     */
    private Integer countryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countryname
     *
     * @mbggenerated
     */
    private String countryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countryid
     *
     * @return the value of country.countryid
     *
     * @mbggenerated
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countryid
     *
     * @param countryid the value for country.countryid
     *
     * @mbggenerated
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countryname
     *
     * @return the value of country.countryname
     *
     * @mbggenerated
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countryname
     *
     * @param countryname the value for country.countryname
     *
     * @mbggenerated
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname == null ? null : countryname.trim();
    }
}