package postgres.entity;

public class State {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.stateid
     *
     * @mbggenerated
     */
    private Integer stateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.statename
     *
     * @mbggenerated
     */
    private String statename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.countryid
     *
     * @mbggenerated
     */
    private Integer countryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.stateid
     *
     * @return the value of state.stateid
     *
     * @mbggenerated
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.stateid
     *
     * @param stateid the value for state.stateid
     *
     * @mbggenerated
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.statename
     *
     * @return the value of state.statename
     *
     * @mbggenerated
     */
    public String getStatename() {
        return statename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.statename
     *
     * @param statename the value for state.statename
     *
     * @mbggenerated
     */
    public void setStatename(String statename) {
        this.statename = statename == null ? null : statename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.countryid
     *
     * @return the value of state.countryid
     *
     * @mbggenerated
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.countryid
     *
     * @param countryid the value for state.countryid
     *
     * @mbggenerated
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }
}